# Generated by Django 3.2 on 2021-05-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_entrada', models.DateField()),
                ('Fecha_salida', models.DateField()),
                ('registro', models.DateTimeField()),
            ],
        ),
    ]
