# Generated by Django 3.2 on 2021-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0002_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='nombre',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
