# Generated by Django 3.2 on 2021-05-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0003_registro_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_control', models.IntegerField(max_length=10)),
                ('nombre', models.CharField(max_length=32)),
                ('Fecha_entrada', models.DateField()),
                ('Fecha_salida', models.DateField()),
                ('registro', models.DateTimeField()),
            ],
        ),
    ]
