# Generated by Django 3.2 on 2021-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0006_alter_usuario_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
